// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ingest

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ingest_flowBanKey struct {
	_    structs.HostLayout
	Addr struct {
		_    structs.HostLayout
		Addr struct {
			_  structs.HostLayout
			V4 uint32
			_  [12]byte
		}
	}
	Family   uint8
	KeyClass uint8
	_        [2]byte
}

type ingest_flowBanVal struct {
	_          structs.HostLayout
	UntilTs    uint64
	Tier       uint8
	Pad        uint8
	ReasonCode uint16
	_          [4]byte
}

type ingest_flowFlowKey struct {
	_     structs.HostLayout
	Saddr struct {
		_    structs.HostLayout
		Addr struct {
			_  structs.HostLayout
			V4 uint32
			_  [12]byte
		}
	}
	Daddr struct {
		_    structs.HostLayout
		Addr struct {
			_  structs.HostLayout
			V4 uint32
			_  [12]byte
		}
	}
	Sport  uint16
	Dport  uint16
	Family uint8
	_      [3]byte
}

type ingest_flowFlowStat struct {
	_        structs.HostLayout
	SynTs    uint64
	ReqBytes uint32
	SegCount uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	ingest_flowMapBanTable      = "ban_table"
	ingest_flowMapEvents        = "events"
	ingest_flowMapFlowStats     = "flow_stats"
	ingest_flowMapLostEvents    = "lost_events"
	ingest_flowProgTcIngressWaf = "tc_ingress_waf"
)

// loadIngest_flow returns the embedded CollectionSpec for ingest_flow.
func loadIngest_flow() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Ingest_flowBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ingest_flow: %w", err)
	}

	return spec, err
}

// loadIngest_flowObjects loads ingest_flow and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ingest_flowObjects
//	*ingest_flowPrograms
//	*ingest_flowMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadIngest_flowObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadIngest_flow()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ingest_flowSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ingest_flowSpecs struct {
	ingest_flowProgramSpecs
	ingest_flowMapSpecs
	ingest_flowVariableSpecs
}

// ingest_flowProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ingest_flowProgramSpecs struct {
	TcIngressWaf *ebpf.ProgramSpec `ebpf:"tc_ingress_waf"`
}

// ingest_flowMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ingest_flowMapSpecs struct {
	BanTable   *ebpf.MapSpec `ebpf:"ban_table"`
	Events     *ebpf.MapSpec `ebpf:"events"`
	FlowStats  *ebpf.MapSpec `ebpf:"flow_stats"`
	LostEvents *ebpf.MapSpec `ebpf:"lost_events"`
}

// ingest_flowVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ingest_flowVariableSpecs struct {
}

// ingest_flowObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadIngest_flowObjects or ebpf.CollectionSpec.LoadAndAssign.
type ingest_flowObjects struct {
	ingest_flowPrograms
	ingest_flowMaps
	ingest_flowVariables
}

func (o *ingest_flowObjects) Close() error {
	return _Ingest_flowClose(
		&o.ingest_flowPrograms,
		&o.ingest_flowMaps,
	)
}

// ingest_flowMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadIngest_flowObjects or ebpf.CollectionSpec.LoadAndAssign.
type ingest_flowMaps struct {
	BanTable   *ebpf.Map `ebpf:"ban_table"`
	Events     *ebpf.Map `ebpf:"events"`
	FlowStats  *ebpf.Map `ebpf:"flow_stats"`
	LostEvents *ebpf.Map `ebpf:"lost_events"`
}

func (m *ingest_flowMaps) Close() error {
	return _Ingest_flowClose(
		m.BanTable,
		m.Events,
		m.FlowStats,
		m.LostEvents,
	)
}

// ingest_flowVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadIngest_flowObjects or ebpf.CollectionSpec.LoadAndAssign.
type ingest_flowVariables struct {
}

// ingest_flowPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadIngest_flowObjects or ebpf.CollectionSpec.LoadAndAssign.
type ingest_flowPrograms struct {
	TcIngressWaf *ebpf.Program `ebpf:"tc_ingress_waf"`
}

func (p *ingest_flowPrograms) Close() error {
	return _Ingest_flowClose(
		p.TcIngressWaf,
	)
}

func _Ingest_flowClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ingest_flow_x86_bpfel.o
var _Ingest_flowBytes []byte
