//go:build !ignore_autogenerated

// Code generated by controller-gen v0.19.0. DO NOT EDIT.

// Package v1alpha1 contains API Schema definitions for the trishula.security
// v1alpha1 API group.
package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver,
// writing into out. in must be non-nil.
func (in *PolicyModeFlags) DeepCopyInto(out *PolicyModeFlags) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver,
// creating a new PolicyModeFlags.
func (in *PolicyModeFlags) DeepCopy() *PolicyModeFlags {
	if in == nil {
		return nil
	}
	out := new(PolicyModeFlags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver,
// writing into out. in must be non-nil.
func (in *RuleSetRef) DeepCopyInto(out *RuleSetRef) {
	*out = *in
	out.Source = in.Source
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver,
// creating a new RuleSetRef.
func (in *RuleSetRef) DeepCopy() *RuleSetRef {
	if in == nil {
		return nil
	}
	out := new(RuleSetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver,
// writing into out. in must be non-nil.
func (in *RuleSetSource) DeepCopyInto(out *RuleSetSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver,
// creating a new RuleSetSource.
func (in *RuleSetSource) DeepCopy() *RuleSetSource {
	if in == nil {
		return nil
	}
	out := new(RuleSetSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver,
// writing into out. in must be non-nil.
func (in *WAFPolicySpec) DeepCopyInto(out *WAFPolicySpec) {
	*out = *in
	if in.RuleSets != nil {
		in, out := &in.RuleSets, &out.RuleSets
		*out = make([]RuleSetRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver,
// creating a new WAFPolicySpec.
func (in *WAFPolicySpec) DeepCopy() *WAFPolicySpec {
	if in == nil {
		return nil
	}
	out := new(WAFPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver,
// writing into out. in must be non-nil.
func (in *WAFPolicy) DeepCopyInto(out *WAFPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver,
// creating a new WAFPolicy.
func (in *WAFPolicy) DeepCopy() *WAFPolicy {
	if in == nil {
		return nil
	}
	out := new(WAFPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver,
// creating a new runtime.Object.
func (in *WAFPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver,
// writing into out. in must be non-nil.
func (in *WAFPolicyList) DeepCopyInto(out *WAFPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WAFPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver,
// creating a new WAFPolicyList.
func (in *WAFPolicyList) DeepCopy() *WAFPolicyList {
	if in == nil {
		return nil
	}
	out := new(WAFPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver,
// creating a new runtime.Object.
func (in *WAFPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
