// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package banenforce

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ban_enforceBansV4Key struct {
	_        structs.HostLayout
	Saddr    uint32
	Family   uint8
	KeyClass uint8
	Pad      uint16
}

type ban_enforceBansV4Val struct {
	_          structs.HostLayout
	BanUntilMs uint64
	Score      uint16
	ReasonCode uint16
	Pad        uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	ban_enforceMapBanStats = "ban_stats"
	ban_enforceMapBansV4   = "bans_v4"
	ban_enforceProgBanXdp  = "ban_xdp"
)

// loadBan_enforce returns the embedded CollectionSpec for ban_enforce.
func loadBan_enforce() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Ban_enforceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ban_enforce: %w", err)
	}

	return spec, err
}

// loadBan_enforceObjects loads ban_enforce and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ban_enforceObjects
//	*ban_enforcePrograms
//	*ban_enforceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBan_enforceObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBan_enforce()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ban_enforceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ban_enforceSpecs struct {
	ban_enforceProgramSpecs
	ban_enforceMapSpecs
	ban_enforceVariableSpecs
}

// ban_enforceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ban_enforceProgramSpecs struct {
	BanXdp *ebpf.ProgramSpec `ebpf:"ban_xdp"`
}

// ban_enforceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ban_enforceMapSpecs struct {
	BanStats *ebpf.MapSpec `ebpf:"ban_stats"`
	BansV4   *ebpf.MapSpec `ebpf:"bans_v4"`
}

// ban_enforceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ban_enforceVariableSpecs struct {
}

// ban_enforceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBan_enforceObjects or ebpf.CollectionSpec.LoadAndAssign.
type ban_enforceObjects struct {
	ban_enforcePrograms
	ban_enforceMaps
	ban_enforceVariables
}

func (o *ban_enforceObjects) Close() error {
	return _Ban_enforceClose(
		&o.ban_enforcePrograms,
		&o.ban_enforceMaps,
	)
}

// ban_enforceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBan_enforceObjects or ebpf.CollectionSpec.LoadAndAssign.
type ban_enforceMaps struct {
	BanStats *ebpf.Map `ebpf:"ban_stats"`
	BansV4   *ebpf.Map `ebpf:"bans_v4"`
}

func (m *ban_enforceMaps) Close() error {
	return _Ban_enforceClose(
		m.BanStats,
		m.BansV4,
	)
}

// ban_enforceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBan_enforceObjects or ebpf.CollectionSpec.LoadAndAssign.
type ban_enforceVariables struct {
}

// ban_enforcePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBan_enforceObjects or ebpf.CollectionSpec.LoadAndAssign.
type ban_enforcePrograms struct {
	BanXdp *ebpf.Program `ebpf:"ban_xdp"`
}

func (p *ban_enforcePrograms) Close() error {
	return _Ban_enforceClose(
		p.BanXdp,
	)
}

func _Ban_enforceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ban_enforce_arm64_bpfel.o
var _Ban_enforceBytes []byte
