// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package tier

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tier_xdpBansV4Key struct {
	_        structs.HostLayout
	Saddr    uint32
	Family   uint8
	KeyClass uint8
	Pad      uint16
}

type tier_xdpBansV4Val struct {
	_          structs.HostLayout
	BanUntilMs uint64
	Score      uint16
	ReasonCode uint16
	Pad        uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tier_xdpMapBanStats = "ban_stats"
	tier_xdpMapBansV4   = "bans_v4"
	tier_xdpProgBanXdp  = "ban_xdp"
)

// loadTier_xdp returns the embedded CollectionSpec for tier_xdp.
func loadTier_xdp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Tier_xdpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tier_xdp: %w", err)
	}

	return spec, err
}

// loadTier_xdpObjects loads tier_xdp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tier_xdpObjects
//	*tier_xdpPrograms
//	*tier_xdpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTier_xdpObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTier_xdp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tier_xdpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tier_xdpSpecs struct {
	tier_xdpProgramSpecs
	tier_xdpMapSpecs
	tier_xdpVariableSpecs
}

// tier_xdpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tier_xdpProgramSpecs struct {
	BanXdp *ebpf.ProgramSpec `ebpf:"ban_xdp"`
}

// tier_xdpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tier_xdpMapSpecs struct {
	BanStats *ebpf.MapSpec `ebpf:"ban_stats"`
	BansV4   *ebpf.MapSpec `ebpf:"bans_v4"`
}

// tier_xdpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tier_xdpVariableSpecs struct {
}

// tier_xdpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTier_xdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tier_xdpObjects struct {
	tier_xdpPrograms
	tier_xdpMaps
	tier_xdpVariables
}

func (o *tier_xdpObjects) Close() error {
	return _Tier_xdpClose(
		&o.tier_xdpPrograms,
		&o.tier_xdpMaps,
	)
}

// tier_xdpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTier_xdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tier_xdpMaps struct {
	BanStats *ebpf.Map `ebpf:"ban_stats"`
	BansV4   *ebpf.Map `ebpf:"bans_v4"`
}

func (m *tier_xdpMaps) Close() error {
	return _Tier_xdpClose(
		m.BanStats,
		m.BansV4,
	)
}

// tier_xdpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTier_xdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tier_xdpVariables struct {
}

// tier_xdpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTier_xdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tier_xdpPrograms struct {
	BanXdp *ebpf.Program `ebpf:"ban_xdp"`
}

func (p *tier_xdpPrograms) Close() error {
	return _Tier_xdpClose(
		p.BanXdp,
	)
}

func _Tier_xdpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tier_xdp_x86_bpfel.o
var _Tier_xdpBytes []byte
