// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package tier

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tier_probeBanKey struct {
	_    structs.HostLayout
	Addr struct {
		_    structs.HostLayout
		Addr struct {
			_  structs.HostLayout
			V4 uint32
			_  [12]byte
		}
	}
	Family   uint8
	KeyClass uint8
	_        [2]byte
}

type tier_probeBanVal struct {
	_          structs.HostLayout
	UntilTs    uint64
	Tier       uint8
	Pad        uint8
	ReasonCode uint16
	_          [4]byte
}

type tier_probeFlowKey struct {
	_     structs.HostLayout
	Saddr struct {
		_    structs.HostLayout
		Addr struct {
			_  structs.HostLayout
			V4 uint32
			_  [12]byte
		}
	}
	Daddr struct {
		_    structs.HostLayout
		Addr struct {
			_  structs.HostLayout
			V4 uint32
			_  [12]byte
		}
	}
	Sport  uint16
	Dport  uint16
	Family uint8
	_      [3]byte
}

type tier_probeFlowStat struct {
	_        structs.HostLayout
	SynTs    uint64
	ReqBytes uint32
	SegCount uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tier_probeMapBanTable      = "ban_table"
	tier_probeMapEvents        = "events"
	tier_probeMapFlowStats     = "flow_stats"
	tier_probeMapLostEvents    = "lost_events"
	tier_probeMapProbeStats    = "probe_stats"
	tier_probeProgTcIngressWaf = "tc_ingress_waf"
)

// loadTier_probe returns the embedded CollectionSpec for tier_probe.
func loadTier_probe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Tier_probeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tier_probe: %w", err)
	}

	return spec, err
}

// loadTier_probeObjects loads tier_probe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tier_probeObjects
//	*tier_probePrograms
//	*tier_probeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTier_probeObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTier_probe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tier_probeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tier_probeSpecs struct {
	tier_probeProgramSpecs
	tier_probeMapSpecs
	tier_probeVariableSpecs
}

// tier_probeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tier_probeProgramSpecs struct {
	TcIngressWaf *ebpf.ProgramSpec `ebpf:"tc_ingress_waf"`
}

// tier_probeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tier_probeMapSpecs struct {
	BanTable   *ebpf.MapSpec `ebpf:"ban_table"`
	Events     *ebpf.MapSpec `ebpf:"events"`
	FlowStats  *ebpf.MapSpec `ebpf:"flow_stats"`
	LostEvents *ebpf.MapSpec `ebpf:"lost_events"`
	ProbeStats *ebpf.MapSpec `ebpf:"probe_stats"`
}

// tier_probeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tier_probeVariableSpecs struct {
}

// tier_probeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTier_probeObjects or ebpf.CollectionSpec.LoadAndAssign.
type tier_probeObjects struct {
	tier_probePrograms
	tier_probeMaps
	tier_probeVariables
}

func (o *tier_probeObjects) Close() error {
	return _Tier_probeClose(
		&o.tier_probePrograms,
		&o.tier_probeMaps,
	)
}

// tier_probeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTier_probeObjects or ebpf.CollectionSpec.LoadAndAssign.
type tier_probeMaps struct {
	BanTable   *ebpf.Map `ebpf:"ban_table"`
	Events     *ebpf.Map `ebpf:"events"`
	FlowStats  *ebpf.Map `ebpf:"flow_stats"`
	LostEvents *ebpf.Map `ebpf:"lost_events"`
	ProbeStats *ebpf.Map `ebpf:"probe_stats"`
}

func (m *tier_probeMaps) Close() error {
	return _Tier_probeClose(
		m.BanTable,
		m.Events,
		m.FlowStats,
		m.LostEvents,
		m.ProbeStats,
	)
}

// tier_probeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTier_probeObjects or ebpf.CollectionSpec.LoadAndAssign.
type tier_probeVariables struct {
}

// tier_probePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTier_probeObjects or ebpf.CollectionSpec.LoadAndAssign.
type tier_probePrograms struct {
	TcIngressWaf *ebpf.Program `ebpf:"tc_ingress_waf"`
}

func (p *tier_probePrograms) Close() error {
	return _Tier_probeClose(
		p.TcIngressWaf,
	)
}

func _Tier_probeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tier_probe_x86_bpfel.o
var _Tier_probeBytes []byte
