// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package shield

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpf_shieldAcl4Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type bpf_shieldBanKey struct {
	_    structs.HostLayout
	Addr struct {
		_  structs.HostLayout
		V4 uint32
		_  [12]byte
	}
	Family   uint8
	KeyClass uint8
	_        [2]byte
}

type bpf_shieldBanVal struct {
	_          structs.HostLayout
	UntilTs    uint64
	Tier       uint8
	Pad        uint8
	ReasonCode uint16
	_          [4]byte
}

type bpf_shieldVerdictKey struct {
	_    structs.HostLayout
	Addr struct {
		_  structs.HostLayout
		V4 uint32
		_  [12]byte
	}
	Family    uint8
	_         [1]byte
	PortClass uint16
}

type bpf_shieldVerdictVal struct {
	_       structs.HostLayout
	Action  uint8
	_       [7]byte
	UntilTs uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpf_shieldMapAcl4         = "acl4"
	bpf_shieldMapBanTable     = "ban_table"
	bpf_shieldMapVerdictCache = "verdict_cache"
	bpf_shieldProgShieldXdp   = "shield_xdp"
)

// loadBpf_shield returns the embedded CollectionSpec for bpf_shield.
func loadBpf_shield() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Bpf_shieldBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf_shield: %w", err)
	}

	return spec, err
}

// loadBpf_shieldObjects loads bpf_shield and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpf_shieldObjects
//	*bpf_shieldPrograms
//	*bpf_shieldMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpf_shieldObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf_shield()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpf_shieldSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_shieldSpecs struct {
	bpf_shieldProgramSpecs
	bpf_shieldMapSpecs
	bpf_shieldVariableSpecs
}

// bpf_shieldProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_shieldProgramSpecs struct {
	ShieldXdp *ebpf.ProgramSpec `ebpf:"shield_xdp"`
}

// bpf_shieldMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_shieldMapSpecs struct {
	Acl4         *ebpf.MapSpec `ebpf:"acl4"`
	BanTable     *ebpf.MapSpec `ebpf:"ban_table"`
	VerdictCache *ebpf.MapSpec `ebpf:"verdict_cache"`
}

// bpf_shieldVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_shieldVariableSpecs struct {
}

// bpf_shieldObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpf_shieldObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_shieldObjects struct {
	bpf_shieldPrograms
	bpf_shieldMaps
	bpf_shieldVariables
}

func (o *bpf_shieldObjects) Close() error {
	return _Bpf_shieldClose(
		&o.bpf_shieldPrograms,
		&o.bpf_shieldMaps,
	)
}

// bpf_shieldMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpf_shieldObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_shieldMaps struct {
	Acl4         *ebpf.Map `ebpf:"acl4"`
	BanTable     *ebpf.Map `ebpf:"ban_table"`
	VerdictCache *ebpf.Map `ebpf:"verdict_cache"`
}

func (m *bpf_shieldMaps) Close() error {
	return _Bpf_shieldClose(
		m.Acl4,
		m.BanTable,
		m.VerdictCache,
	)
}

// bpf_shieldVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpf_shieldObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_shieldVariables struct {
}

// bpf_shieldPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpf_shieldObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_shieldPrograms struct {
	ShieldXdp *ebpf.Program `ebpf:"shield_xdp"`
}

func (p *bpf_shieldPrograms) Close() error {
	return _Bpf_shieldClose(
		p.ShieldXdp,
	)
}

func _Bpf_shieldClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_shield_arm64_bpfel.o
var _Bpf_shieldBytes []byte
